### ISSUE TITLE
Error in Quiver Snippets Action

### ISSUE THREAD

**Issue by JMichaelTX** [raguay/MyLaunchBarActions#3]
Running:  LaunchBar 6.7.2 (6136) on macOS 10.11.4
### After I sent my Quiver Lib to the Action:

![image](https://cloud.githubusercontent.com/assets/11052885/19254634/3b11edec-8f1b-11e6-8b16-467ec70f80df.png)
### When I try to drill down into Quiver Snippets via the [RIGHT ARROW] key:

![image](https://cloud.githubusercontent.com/assets/11052885/19254644/50eae83a-8f1b-11e6-9563-493ece450857.png)

**Comment by raguay** [comment]
Hi,

Thanks for trying out the workflow. I've had zero responses from others. I think you are the only other person using it. Thanks for the feedback.

Okay, I just made a few changes that should fix the issues. Due to me being the author, I did not check all edge cases. Sorry. Please re-download and reload the action.

I do not know how to download just a single item in a GitHub repository. I've seen others do it, asked them how, but I never get a response. So, just download the whole repository, unzip it, and double click on the action you want. It will then be loaded into Launchbar.

To be frank, I do not use Launchbar much. My main program to use is Alfred and Keyboard Maestro. I have the some workflow for Quiver in Alfred (but it has much more features. I plan to add them to Launchbar also, but I haven't had the time. Since no one has shown any interest in it, I've let it lag behind).

You will have to drill down to the Quiver library file that you want your snippets in and quick send it to this action. Since I always use a separate shared notes file, I forgot to test the other option of using the main library. The code had a typo there (I dropped the "File." from the "getdirectories()" function call). The other error now tells the user that the snippet file wasn't loaded properly.

Yea, I know the instructions are scarce. I meant to update and expand them, but since I thought I was the only one using it, it got shoved down in my priorities.

Thanks for all the testing and helpful comments. Please let me know how this works for you now.

Richard

**Comment by raguay** [comment]
I haven't heard back. I'm assume that fixed it for you. Please let me know if not. Otherwise, I'm closing this ticket.
